"""Make changes in booking schema

Revision ID: 11d53df58ede
Revises: 6312069af841
Create Date: 2024-10-18 14:39:58.537299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11d53df58ede'
down_revision = '6312069af841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('booking', 'pickup_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('booking', 'dropoff_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'dropoff_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('booking', 'pickup_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('booking', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
