"""Update user_id to owner_id

Revision ID: 6312069af841
Revises: e04abbd12983
Create Date: 2024-10-16 20:00:13.783094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6312069af841'
down_revision = 'e04abbd12983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.drop_constraint('booking_user_id_fkey', 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'user', ['owner_id'], ['user_id'])
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key('booking_user_id_fkey', 'booking', 'user', ['user_id'], ['user_id'])
    op.drop_column('booking', 'owner_id')
    # ### end Alembic commands ###
