"""Update schema

Revision ID: e04abbd12983
Revises: 1dadbe65d70d
Create Date: 2024-10-14 21:00:27.716033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e04abbd12983'
down_revision = '1dadbe65d70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'estimated_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('booking', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('driver', sa.Column('vehicle_type_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'driver', 'vehicletype', ['vehicle_type_id'], ['vehicle_type_id'])
    op.alter_column('payment', 'booking_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'payment', ['booking_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.alter_column('payment', 'booking_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.drop_column('driver', 'vehicle_type_id')
    op.alter_column('booking', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('booking', 'estimated_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
